[workspace]
members = [
    "programs/fuse"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
strip = true

[profile.release.build-override]
opt-level = "z"
incremental = false
codegen-units = 1
